#!/usr/bin/env tsx
/**
 * Track SQL Generator
 *
 * Generates a SQL migration file from a structured track definition.
 * This script is used to convert research into deployable curriculum.
 *
 * Usage:
 *   npx tsx scripts/generate-track-sql.ts <track-file.json> [output-name]
 *
 * Example:
 *   npx tsx scripts/generate-track-sql.ts tracks/art-history.json art-history
 *
 * The track JSON file should follow this structure:
 * {
 *   "track": {
 *     "id": "art-history",
 *     "name": "Art History",
 *     "description": "Learn to analyze and understand art...",
 *     "language": null,
 *     "domain": "humanities",
 *     "difficulty": "beginner"
 *   },
 *   "concepts": [
 *     {
 *       "id": "visual-analysis",
 *       "name": "Visual Analysis",
 *       "category": "Foundations",
 *       "cluster": null,
 *       "prerequisites": [],
 *       "sandbox_id": null
 *     }
 *   ],
 *   "projects": [
 *     {
 *       "id": "museum-guide",
 *       "sequence_order": 1,
 *       "name": "Personal Museum Guide",
 *       "description": "Build a guide to your favorite artworks...",
 *       "estimated_hours": 10,
 *       "milestones": [
 *         {"id": 1, "name": "Select Works", "description": "Choose 5 artworks"}
 *       ],
 *       "milestone_concepts": [
 *         {"milestone": 1, "concept_id": "visual-analysis", "relationship": "introduces"}
 *       ]
 *     }
 *   ],
 *   "misconceptions": [],
 *   "diagnostic_questions": [],
 *   "sandboxes": []
 * }
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface TrackDefinition {
  id: string;
  name: string;
  description: string;
  language: string | null;
  domain: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

interface ConceptDefinition {
  id: string;
  name: string;
  category: string;
  cluster: string | null;
  prerequisites: string[];
  sandbox_id: string | null;
}

interface MilestoneDefinition {
  id: number;
  name: string;
  description: string;
}

interface MilestoneConceptDefinition {
  milestone: number;
  concept_id: string;
  relationship: 'introduces' | 'requires' | 'reinforces';
}

interface ProjectDefinition {
  id: string;
  sequence_order: number;
  name: string;
  description: string;
  estimated_hours: number;
  milestones: MilestoneDefinition[];
  milestone_concepts: MilestoneConceptDefinition[];
}

interface MisconceptionDefinition {
  id: string;
  concept_id: string;
  name: string;
  description: string;
  trigger_answer: string;
  remediation_strategy: string;
  contrasting_case: object | null;
}

interface DiagnosticQuestionDefinition {
  id: string;
  concept_id: string;
  code_snippet: string;
  prompt: string;
  correct_answer: string;
  distractors: Array<{ answer: string; misconception_id: string | null }>;
}

interface SandboxDefinition {
  id: string;
  concept_id: string;
  name: string;
  description: string;
  starter_code: string;
  expected_failure: string;
  learning_goal: string;
}

interface TrackFile {
  track: TrackDefinition;
  concepts: ConceptDefinition[];
  projects: ProjectDefinition[];
  misconceptions?: MisconceptionDefinition[];
  diagnostic_questions?: DiagnosticQuestionDefinition[];
  sandboxes?: SandboxDefinition[];
}

function escapeSQL(value: string | null): string {
  if (value === null) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function generateSQL(trackData: TrackFile, migrationName: string): string {
  const lines: string[] = [];
  const timestamp = new Date().toISOString();

  lines.push(`-- Migration: ${migrationName}`);
  lines.push(`-- Track: ${trackData.track.name}`);
  lines.push(`-- Generated: ${timestamp}`);
  lines.push(`-- This file was auto-generated by scripts/generate-track-sql.ts`);
  lines.push('');

  // Track
  lines.push('-- =============================================================================');
  lines.push('-- Learning Track');
  lines.push('-- =============================================================================');
  lines.push('');
  const t = trackData.track;
  lines.push(`INSERT OR REPLACE INTO learning_track (id, name, description, language, domain, difficulty, is_preseeded, created_by)`);
  lines.push(`VALUES (${escapeSQL(t.id)}, ${escapeSQL(t.name)}, ${escapeSQL(t.description)}, ${escapeSQL(t.language)}, ${escapeSQL(t.domain)}, ${escapeSQL(t.difficulty)}, TRUE, 'system');`);
  lines.push('');

  // Concepts
  if (trackData.concepts.length > 0) {
    lines.push('-- =============================================================================');
    lines.push(`-- Concepts (${trackData.concepts.length} total)`);
    lines.push('-- =============================================================================');
    lines.push('');
    for (const c of trackData.concepts) {
      const prereqs = JSON.stringify(c.prerequisites);
      lines.push(`INSERT OR REPLACE INTO concept (id, name, category, cluster, prerequisites, sandbox_id)`);
      lines.push(`VALUES (${escapeSQL(c.id)}, ${escapeSQL(c.name)}, ${escapeSQL(c.category)}, ${escapeSQL(c.cluster)}, ${escapeSQL(prereqs)}, ${escapeSQL(c.sandbox_id)});`);
    }
    lines.push('');
  }

  // Sandboxes
  if (trackData.sandboxes && trackData.sandboxes.length > 0) {
    lines.push('-- =============================================================================');
    lines.push(`-- Sandboxes (${trackData.sandboxes.length} total)`);
    lines.push('-- =============================================================================');
    lines.push('');
    for (const s of trackData.sandboxes) {
      lines.push(`INSERT OR REPLACE INTO sandbox (id, concept_id, name, description, starter_code, expected_failure, learning_goal)`);
      lines.push(`VALUES (${escapeSQL(s.id)}, ${escapeSQL(s.concept_id)}, ${escapeSQL(s.name)}, ${escapeSQL(s.description)}, ${escapeSQL(s.starter_code)}, ${escapeSQL(s.expected_failure)}, ${escapeSQL(s.learning_goal)});`);
    }
    lines.push('');
  }

  // Projects
  if (trackData.projects.length > 0) {
    lines.push('-- =============================================================================');
    lines.push(`-- Project Templates (${trackData.projects.length} total)`);
    lines.push('-- =============================================================================');
    lines.push('');
    for (const p of trackData.projects) {
      const milestones = JSON.stringify(p.milestones);
      lines.push(`INSERT OR REPLACE INTO project_template (id, track_id, sequence_order, name, description, estimated_hours, milestones)`);
      lines.push(`VALUES (${escapeSQL(p.id)}, ${escapeSQL(t.id)}, ${p.sequence_order}, ${escapeSQL(p.name)}, ${escapeSQL(p.description)}, ${p.estimated_hours}, ${escapeSQL(milestones)});`);
    }
    lines.push('');

    // Milestone-Concept mappings
    const allMappings = trackData.projects.flatMap(p =>
      p.milestone_concepts.map(mc => ({ project_id: p.id, ...mc }))
    );
    if (allMappings.length > 0) {
      lines.push('-- =============================================================================');
      lines.push(`-- Milestone-Concept Mappings (${allMappings.length} total)`);
      lines.push('-- =============================================================================');
      lines.push('');
      for (const mc of allMappings) {
        lines.push(`INSERT OR REPLACE INTO milestone_concept (project_template_id, milestone_number, concept_id, relationship)`);
        lines.push(`VALUES (${escapeSQL(mc.project_id)}, ${mc.milestone}, ${escapeSQL(mc.concept_id)}, ${escapeSQL(mc.relationship)});`);
      }
      lines.push('');
    }
  }

  // Misconceptions
  if (trackData.misconceptions && trackData.misconceptions.length > 0) {
    lines.push('-- =============================================================================');
    lines.push(`-- Misconceptions (${trackData.misconceptions.length} total)`);
    lines.push('-- =============================================================================');
    lines.push('');
    for (const m of trackData.misconceptions) {
      const cc = m.contrasting_case ? JSON.stringify(m.contrasting_case) : null;
      lines.push(`INSERT OR REPLACE INTO misconception (id, concept_id, name, description, trigger_answer, remediation_strategy, contrasting_case)`);
      lines.push(`VALUES (${escapeSQL(m.id)}, ${escapeSQL(m.concept_id)}, ${escapeSQL(m.name)}, ${escapeSQL(m.description)}, ${escapeSQL(m.trigger_answer)}, ${escapeSQL(m.remediation_strategy)}, ${escapeSQL(cc)});`);
    }
    lines.push('');
  }

  // Diagnostic Questions
  if (trackData.diagnostic_questions && trackData.diagnostic_questions.length > 0) {
    lines.push('-- =============================================================================');
    lines.push(`-- Diagnostic Questions (${trackData.diagnostic_questions.length} total)`);
    lines.push('-- =============================================================================');
    lines.push('');
    for (const dq of trackData.diagnostic_questions) {
      const distractors = JSON.stringify(dq.distractors);
      lines.push(`INSERT OR REPLACE INTO diagnostic_question (id, concept_id, code_snippet, prompt, correct_answer, distractors)`);
      lines.push(`VALUES (${escapeSQL(dq.id)}, ${escapeSQL(dq.concept_id)}, ${escapeSQL(dq.code_snippet)}, ${escapeSQL(dq.prompt)}, ${escapeSQL(dq.correct_answer)}, ${escapeSQL(distractors)});`);
    }
    lines.push('');
  }

  lines.push('-- End of track: ' + trackData.track.name);
  lines.push('');

  return lines.join('\n');
}

// CLI Entry Point
async function main() {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.log(`
Track SQL Generator - Convert research into curriculum SQL

Usage:
  npx tsx scripts/generate-track-sql.ts <track-file.json> [output-name]

Arguments:
  track-file.json   Path to the track definition JSON file
  output-name       Optional: name for the migration (default: track ID)

Example:
  npx tsx scripts/generate-track-sql.ts tracks/art-history.json
  npx tsx scripts/generate-track-sql.ts tracks/problem-solving.json problem-solving

The script will:
1. Read the track JSON definition
2. Generate a SQL migration file
3. Save it to src/server/db/migrations/

See the track template at tracks/template.json for the expected format.
    `);
    process.exit(0);
  }

  const inputPath = args[0];
  const outputName = args[1];

  if (!existsSync(inputPath)) {
    console.error(`Error: File not found: ${inputPath}`);
    process.exit(1);
  }

  try {
    const content = readFileSync(inputPath, 'utf-8');
    const trackData: TrackFile = JSON.parse(content);

    // Validate required fields
    if (!trackData.track || !trackData.track.id) {
      console.error('Error: Track must have an id');
      process.exit(1);
    }

    const migrationName = outputName || trackData.track.id;

    // Get the next migration number
    const migrationsDir = join(__dirname, '..', 'src', 'server', 'db', 'migrations');
    const { readdirSync } = await import('fs');
    const files = existsSync(migrationsDir)
      ? readdirSync(migrationsDir).filter((f: string) => f.endsWith('.sql'))
      : [];

    const maxNum = files.reduce((max: number, f: string) => {
      const match = f.match(/^(\d+)_/);
      return match ? Math.max(max, parseInt(match[1])) : max;
    }, 0);

    const nextNum = String(maxNum + 1).padStart(3, '0');
    const outputFileName = `${nextNum}_track_${migrationName}.sql`;
    const outputPath = join(migrationsDir, outputFileName);

    const sql = generateSQL(trackData, outputFileName);
    writeFileSync(outputPath, sql);

    console.log(`✓ Generated: ${outputPath}`);
    console.log(`  Track: ${trackData.track.name}`);
    console.log(`  Concepts: ${trackData.concepts.length}`);
    console.log(`  Projects: ${trackData.projects.length}`);
    if (trackData.misconceptions) {
      console.log(`  Misconceptions: ${trackData.misconceptions.length}`);
    }
    if (trackData.diagnostic_questions) {
      console.log(`  Diagnostics: ${trackData.diagnostic_questions.length}`);
    }
    console.log(`\nTo apply: The migration will run automatically when Avaia starts.`);
    console.log(`To publish: Update package.json version and run 'npm publish'`);

  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

main().catch(console.error);
